services:
    products-service:
        build: ./products
        volumes:
            - ./products:/usr/src/app
        ports:
            - 5001:8080
        depends_on:
            products-database

    products-view:
        build: ./products-view
        volumes:
            - ./products-view:/usr/src/app
        ports:
            - 5000:80
        depends_on:
            - products-service
            
    products-database:
        build: ./products-database
        ports:
            - 3306:3306