version: "3"
services:
    products-database:
        build: ./products-database
        ports:
            - 3306:3306

    products-service:
        build: ./products
        ports:
            - 5001:8081
        depends_on:
            - products-database

    products-view:
        build: ./products-view
        ports:
            - 5000:8080
        depends_on:
            - products-service